### ISSUE TITLE
Add how to upload files from browser using presigned url

### ISSUE THREAD

**Issue by waptik** [cloudflare/cloudflare-docs#6411]
### Which Cloudflare product(s) does this pertain to?

R2

### Subject Matter

Example of file upload 

### Content Location

https://developers.cloudflare.com/r2/examples/

### Additional information

With r2 being generally available alongside the introduction of public files, it has opened a new opportunity for devs to upload files from the browser using presigned url instead of doing it server side or using a worker.
But people like have been having issues uploading files directly from the browser due to CORS error as seen when doing a search for “cors” is done in the “r2-storage” channel on discord.
Therefore I think there’s a need for an official working example on how to upload files from the browser using s3 presigned url api, aside the need for documentation on cors(https://github.com/cloudflare/cloudflare-docs/issues/6003)

**Comment by JasoonX** [comment]
Really need this one

**Comment by dcpena** [comment]
This should be addressed as of PR https://github.com/cloudflare/cloudflare-docs/pull/7574 which adds more extensive docs on CORS.

**Comment by samal-rasmussen** [comment]
It's great that there's more documentation on cors, but I still don't know how to upload from the browser to a presigned url 🤷‍♂️

EDIT: Found an end to end example here: https://annotate.dev/p/hello-world/implementing-user-uploads-with-presigned-urls-RcaRFbkDyop8pl
